### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by Widdershin** [noffle/web-udp#2]
> Are you excited about seeing low-level UDP in the browser? File an issue! Send a PR! Get in contact with @noffle!

I am excited about this! How can I help? What's the plan?

**Comment by noffle** [comment]
You picked a good time to ask! There are some very fruitful discussions happening right now at https://github.com/Maksims/web-udp-public. Taking part in these conversations will, I think, be of great impact to the effort.

**Comment by noffle** [comment]
That said, that effort is about server-client UDP. If you're interested in P2P (a WebRTC replacement), then this repo might be a better place.
