### ISSUE TITLE
This problem has already been solved

### ISSUE THREAD

**Issue by gafferongames** [noffle/web-udp#4]
https://github.com/RedpointGames/netcode.io-browser

**Comment by noffle** [comment]
Thanks @gafferongames! netcode.io looks like an awesome protocol for fast in-browser games!

I did some reading, but still have a couple of questions:

1. Can browsers talk to each other? Peer-to-peer applications are a big motivator for `web-udp`.
2. Is there LAN multicast support? Here I'm thinking about peer discovery on the local network.

**Comment by noffle** [comment]
P.S. I've been a great fan of your game networking articles over the years! :heart:

**Comment by gafferongames** [comment]
Thanks. Good points!

I think that peer-to-peer communications are really complex, and WebRTC solves this really well. I don't think it's possible to get something simple that also handles peer-to-peer, so I am focusing my efforts on client/server communications with dedicated servers (eg. public IP for servers). 

The other reason that I am doing this is that I see games over the past 5 years having a strong trend towards dedicated servers and client/server topology. In that sense, I feel that peer-to-peer is obsolete in gaming.

cheers

- Glenn
